### ISSUE TITLE
Add sensor information for Sonoff TH16

### ISSUE THREAD

**Issue by tsouza85** [mattsaxon/sonoff-lan-mode-homeassistant#11]
Config:
```
switch:
  - platform: sonoff_lan_mode_r3
    device_id: 10007bf475
    api_key: 7d6dff19-fef7-4d11-9094-5658add22c13
```
Log message:

> 2019-12-15 14:03:59 INFO (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] Service type _ewelink._tcp.local. of name eWeLink_10007bf475._ewelink._tcp.local. added
> 2019-12-15 14:03:59 DEBUG (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] service is at 192.168.0.103:8081
> 2019-12-15 14:03:59 DEBUG (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] properties: {b'txtvers': b'1', b'id': b'10007bf475', b'type': b'th_plug', b'apivers': b'1', b'seq': b'569', b'encrypt': True, b'iv': b'MjgwNTY2MjI1NTY0MDUzOQ==', b'data1': b'KZI8x5XJTQKyoXrORx/aINzg8ZBNJ1BuEKuLOIpkscu+AVhoXYpLOh94ViX9MnSYZen/6ta+JdbAAhvkJwDAAuX/c6Bqy1fXJU0JZjrprHrfH5ymcVAqHklshmk0t8OgkKbj6kNyFO1nZIvHKGgHy8mgS1rrPWzwqz5BTVZJ8tGulygjsBIEw96nBQ1sHNdTz7S6K49YThFl2Lv+6ZP5CQ=='}
> 2019-12-15 14:03:59 DEBUG (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] type: b'th_plug'
> 2019-12-15 14:03:59 DEBUG (zeroconf-ServiceBrowser__ewelink._tcp.local.) [homeassistant.components.switch.sonoff_lan_mode_r3] decrypted data: b'{"deviceType":"normal","switch":"off","startup":"off","pulse":"off","pulseWidth":500,"sledOnline":"off","sensorType":"AM2301","humidity":86,"temperature":28}'
> 2019-12-15 14:04:00 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] HassSonoffSwitch returning _name: Sonoff Switch
> 2019-12-15 14:04:00 DEBUG (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] enter handle_mesage()
> 2019-12-15 14:04:00 ERROR (MainThread) [homeassistant.components.switch.sonoff_lan_mode_r3] Unknown message received from device: 

Does not appear as a switch so I can configure the entity. 
What can it be?

**Comment by mattsaxon** [comment]
Added support for TH plug in latest version

**Comment by mattsaxon** [comment]
Here’s the relevant part from the trace....

"humidity":86,
"temperature"28

I need to add these as fields so they are visible in HA

**Comment by tsouza85** [comment]
how?

switchs.yaml
```
- platform: sonoff_lan_mode_r3
  name: Trafo
  device_id: 10007bf475
  api_key: !secret trafo_api_key
  arg:
    - humidity: 86
    - temperature: 28
```
