### ISSUE TITLE
4CH Pro Unavailable channels (but not all) in Home Assistant

### ISSUE THREAD

**Issue by Kalma-House** [mattsaxon/sonoff-lan-mode-homeassistant#24]
HA Version: 105.2
Component: Latest version (1.1.3) (It did not happen in 1.1.1)
Devices: 4CH Pro (2 of them)
Firmware: 3.3.0

```
switch:
  - platform: sonoff_lan_mode_r3
    name: sonoff_4chr2_XXXXXXXXXX_0
    device_id: XXXXXXXXXX
    api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    icon: mdi:lightbulb
    outlet: 0
  - platform: sonoff_lan_mode_r3
    name: sonoff_4chr2_XXXXXXXXXX_1
    device_id: XXXXXXXXXX
    api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    icon: mdi:lightbulb
    outlet: 1
  - platform: sonoff_lan_mode_r3
    name: sonoff_4chr2_XXXXXXXXXX_2
    device_id: XXXXXXXXXX
    api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    icon: mdi:lightbulb
    outlet: 2
  - platform: sonoff_lan_mode_r3
    name: sonoff_4chr2_XXXXXXXXXX_3
    device_id: XXXXXXXXXX
    api_key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    icon: mdi:lightbulb
    outlet: 3
  - platform: sonoff_lan_mode_r3
    name: sonoff_4chr2_YYYYYYYYYY_1
    device_id: YYYYYYYYYY
    api_key: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
    icon: mdi:lightbulb
    outlet: 1
  - platform: sonoff_lan_mode_r3
    name: sonoff_4chr2_YYYYYYYYYY_0
    device_id: YYYYYYYYYY
    api_key: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
    icon: mdi:lightbulb
    outlet: 0
  - platform: sonoff_lan_mode_r3
    name: sonoff_4chr2_YYYYYYYYYY_2
    device_id: YYYYYYYYYY
    api_key: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
    icon: mdi:lightbulb
    outlet: 2
  - platform: sonoff_lan_mode_r3
    name: sonoff_4chr2_YYYYYYYYYY_3
    device_id: YYYYYYYYYY
    api_key: yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy
    icon: mdi:lightbulb
    outlet: 3
```

The 4CH Pro are multichannel devices. About once a day, most (but not all) the channels in each device become unavailable in HA. That seems weird to me. If the devices were really unavailable all the channels should be marked as such (besides,the devices are available in ewelink app). Moreover, as soon as I toggle one of the available channels in HA, the rest of the channels in the device instantly become available. All of this leads me to believe it is a bug in the component, and not a problem in the network.

This is a link to the debug trace, if you are interested:
https://pastebin.com/NrYCkse6

The relevant parts are at times 2020-02-18 23:26:54 (when the devices become unavailable) and 2020-02-18 23:44:31 (when I toggle one of the channels and the rest become available).

Let me know if I can be of further assistance. 
Regards.
Javier
