### ISSUE TITLE
Mini 3.5.0 not working

### ISSUE THREAD

**Issue by Krivega** [mattsaxon/sonoff-lan-mode-homeassistant#27]
Config
```yaml
logger:
  default: warn
  logs:
    custom_components.sonoff_lan_mode_r3: debug

switch:
  - platform: sonoff_lan_mode_r3
    name: sonoff_mini_1
    device_id: 1000983e3c
    icon: mdi:lightbulb
```

Log
```

Logger: custom_components.sonoff_lan_mode_r3.switch
Source: /usr/local/lib/python3.7/site-packages/pysonofflanr3/client.py:201
First occurred: 3:12:10 (5 occurrences)
Last logged: 4:02:05

Missing api_key for encrypted device: eWeLink_1000983e3c._ewelink._tcp.local.
```

in DIY mode 

Maybe this is due to protocol version 2.0?
 https://github.com/itead/Sonoff_Devices_DIY_Tools/blob/master/SONOFF%20DIY%20MODE%20Protocol%20Doc%20v2.0%20Doc.pdf
