### ISSUE TITLE
Sonoff Basic R3 DIY mode labeled as unavaliable on Hassio 0.101.3 

### ISSUE THREAD

**Issue by salvoc81** [mattsaxon/sonoff-lan-mode-homeassistant#7]
When installed the component, the switch is found but it is labeled as ```unavailable```.
Also I am not sure if it is required that the Basic R3 is set to LAN mode before installing the component.

Following is the related part of the configuration file:
```
switch:
  - platform: sonoff_lan_mode_r3
    name: Lampada
    device_id: 1000900a87
    icon: mdi:lightbulb
```

**Comment by mattsaxon** [comment]
There is non need to put it in any mode for LAN to work. However is it in DIY mode? If it is not, you will need the APi key.

**Comment by salvoc81** [comment]
Yes, it is in DIY mode (and the in the eWelink app is shown as offline, as expected).
I am not adding the API because it is in DIY mode.

Do you think it would be better to try with the API Key?
I will see if I can try that.

**Comment by salvoc81** [comment]
I have checked the debug log for the same configuration.
I get an error for the api_key missing.

```
Error decrypting for device 1000900a87: encoding without a string argument, probably wrong API key
```
How can I set an empty api-key?
api_key:[] ?
Sorry for the very simple question

**Comment by salvoc81** [comment]
I confirm I get no errors when in DIY mode and without including the api=key field

**Comment by mattsaxon** [comment]
The api key needs to be absent if In DIY mode. Please post a log of such a configuration

**Comment by salvoc81** [comment]
Actually I do not get any specific error from the log
```
You are using a custom integration for sonoff_lan_mode_r3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
```

Here is the configuration file:
```
switch:
  - platform: sonoff_lan_mode_r3
    name: Lampada
    device_id: 1000900a87
    icon: mdi:lightbulb

logger:
  default: warn
  logs:
    homeassistant.components.switch.sonoff_lan_mode_r3: debug
```
